version: "3"

networks:
  transcendence:
    name: transcendence

volumes:
  frontend_vol:
    driver: local
    driver_opts:
      device: ../Frontend
      o: bind
      type: none

  backend_vol:
    driver: local
    driver_opts:
      device: ../Backend
      o: bind
      type: none

  shared_vol:
    driver: local
    driver_opts:
      device: ../Shared
      o: bind
      type: none

  database_conf_vol:

  database_data_vol:

services:
  database:
    build: ./Database
    container_name: Database
    ports:
      - 5432:5432
    volumes:
      - database_conf_vol:/etc/postgresql/15/
      - database_data_vol:/var/lib/postgresql/15/
    env_file:
      - .env
    networks:
      - transcendence
    restart: always

  backend:
    build: ./Backend
    container_name: Backend
    ports:
      - 4000:4000
    volumes:
      - backend_vol:/nest-project
      - shared_vol:/Shared
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - database
    restart: always

  frontend:
    build: ./Frontend
    container_name: Frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - frontend_vol:/app
      - shared_vol:/Shared
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
