version: "3"

services:

  backend:
    build: ./Backend
    container_name: NestJS
    ports:
      - 
    volumes:
      - 
    env_file:
      - .env
    networks:
      - 
    restart: always

volumes:

networks:
  inception:
