version: "3"

volumes:

  frontend_vol:
    driver: local
    driver_opts:
      device: ../Frontend
      o: bind
      type: none

  backend_vol:
    driver: local
    driver_opts:
      device: ../Backend
      o: bind
      type: none

  database_vol:
    driver: local
    driver_opts:
      device: ../Database
      o: bind
      type: none

services:

  database:
    build: ./Database
    container_name: PostGreSQL
    ports:
      - 2000:2000
    volumes:
      - database_vol:/data
    env_file:
      - .env
    networks:
      - transcendence
    restart: always

  # backend:
  #   build: ./Backend
  #   container_name: NestJS
  #   ports:
  #     - 4000:4000
  #   volumes:
  #     - backend_vol:/nest-project
  #   env_file:
  #     - .env
  #   networks:
  #     - transcendence
  #   restart: always

  # frontend:
  #   build: ./Frontend
  #   container_name: React
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - frontend_vol:/app
  #   env_file:
  #     - .env
  #   networks:
  #     - transcendence
  #   restart: always

networks:
  transcendence:
    name: transcendence
