version: "3"

networks:
  transcendence:
    name: transcendence

volumes:

  frontend_vol:
    driver: local
    driver_opts:
      device: ../Frontend
      o: bind
      type: none

  backend_vol:
    driver: local
    driver_opts:
      device: ../Backend
      o: bind
      type: none

  database_conf_vol:
    driver: local
    driver_opts:
      device: ../Database/conf
      o: bind
      type: none

  database_data_vol:
    driver: local
    driver_opts:
      device: ../Database/data
      o: bind
      type: none

services:

  database:
    build: ./Database
    container_name: Postgresql
    ports:
      - 5432:5432
    volumes:
      - database_conf_vol:/etc/postgresql/13/main
      - database_data_vol:/var/lib/postgresql/13/main
    env_file:
      - .env
    networks:
      - transcendence
    restart: always

  backend:
    build: ./Backend
    container_name: NestJS
    ports:
      - 4000:4000
    volumes:
      - backend_vol:/nest-project
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - database
    restart: always

  frontend:
    build: ./Frontend
    container_name: React
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - frontend_vol:/app
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
