version: "3.8"

networks:
  transcendence:
    name: transcendence

volumes:
  frontend_vol:
    driver: local
    driver_opts:
      device: ../workspaces/Frontend
      o: bind
      type: none

  backend_vol:
    driver: local
    driver_opts:
      device: ../workspaces/Backend
      o: bind
      type: none

  shared_vol:
    driver: local
    driver_opts:
      device: ../workspaces/Shared
      o: bind
      type: none

  database_conf_vol:

  database_data_vol:

services:
  database:
    build: ./Database
    container_name: Database
    ports:
      - 5432:5432
    volumes:
      - database_conf_vol:/etc/postgresql/15/
      - database_data_vol:/var/lib/postgresql/15/
    env_file:
      - .env
    networks:
      - transcendence
    restart: always

  backend:
    build:
      context: ../
      dockerfile: ./Dockers/Backend/Dockerfile
    container_name: Backend
    ports:
      - 4000:4000
    volumes:
      - backend_vol:/workspaces/Backend
      - shared_vol:/workspaces/Shared
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      - database
    restart: always

  frontend:
    build:
      context: ../
      dockerfile: ./Dockers/Frontend/Dockerfile
    container_name: Frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - frontend_vol:/workspaces/Frontend
      - shared_vol:/workspaces/Shared
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
