version: "3"

services:

  backend:
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    ports:
      - "9000"
    volumes:
      - wp_files:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always

  nginx:
    build:
      context: ./requirements/nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_files:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always

volumes:
  wp_files:
  db_files:

networks:
  inception:
