version: "3"

volumes:

  frontend_vol:
    driver: local
    driver_opts:
      device: ../Frontend
      o: bind
      type: none

  backend_vol:
    driver: local
    driver_opts:
      device: ../Backend
      o: bind
      type: none

  database_vol:
    driver: local
    driver_opts:
      device: ../Database
      o: bind
      type: none
      

services:

  backend:
    build: ./Backend
    container_name: NestJS
    env_file:
      - .env
    networks:
      - transcendence
    restart: always

  frontend:
    build: ./Frontend
    container_name: React
    ports:
      - "3000:3000"
    volumes:
      - frontend_vol:/app
    env_file:
      - .env
    networks:
      - transcendence
    restart: always

networks:
  transcendence:
    name: transcendence
